server.port=8082
calculator.url=http://localhost:8081/calculator
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/creditbank
spring.datasource.username=postgres
spring.datasource.password=root
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.liquibase=DEBUG
spring.liquibase.clear-checksums=true