base-rate=20
insurance-rate=3
server.port=8080

springdoc.swagger-ui.default-models-expand-depth=4
springdoc.swagger-ui.default-model-expand-depth=4

logging.level.root=INFO
logging.level.ru.neoflex.bank=INFO
